### ISSUE TITLE
prefixes are being applied to arguments

### ISSUE THREAD

**Issue by toddself** [stackcss/sheetify#80]
trying to use the `:nth-child` pseudo-selector and its not working as expected:

```css
.row {
  border: 1px solid black;
}

.row:nth-child(odd) {
  background-color: #eee;
}
```

```html
<div>
<div class="row">yo!</div>
<div class="row">dude</div>
</div>
```

Should produce:
![image](https://cloud.githubusercontent.com/assets/193412/16529882/1b73161e-3f7a-11e6-91ec-1347cbc454b8.png)

However, when you do this with sheetify, the transformed CSS looks like:

```css
._ffdf2d5a .row {
  border: 1px solid black;
}
._ffdf2d5a .row:nth-child(._ffdf2d5a odd) {
  background-color: #eee;
}
```

Which does not apply the rule to the odd nth-children.  If you add a rule in your inspector omitting the `._ffdf2d5a ` prior to `odd`:

```css
._ffdf2d5a .row:nth-child(odd) {
  background-color: #eee;
}
```

It works as expected.
