### ISSUE TITLE
Readme Example Typo

### ISSUE THREAD

**Issue by lukeed** [stackcss/sheetify#81]
First example, the `prefix` value does not match the "printed" markup.

```css
.[[[ _60ed23ec9f ]]] h1 {
  text-align: center;
}
```

And the rendered HTML includes the namespace:

```html
<section class="[[[ _60ed23e ]]]">
  <h1>My beautiful, centered title</h1>
</section>
```
