### ISSUE TITLE
Support for @apply Rule

### ISSUE THREAD

**Issue by tgfjt** [stackcss/sheetify#91]
Hi! What do you think about `@apply` support?

```css
:root {
  --awesomeComponent-theme: {
    color: white;
    background: black;
  }
}

.awesomeComponent {
  width: 100%;
  margin: 0 auto;
  @apply --awesomeComponent-theme;
}
```
https://www.chromestatus.com/feature/5753701012602880

ref: #87 
if we can use plugin, resolve with postcss-apply.
